#!/usr/bin/python
import sys

from charmhelpers.core import hookenv, host

if __name__ == "__main__":
    if not host.service_pause("mysql"):
        hookenv.action_fail("Failed to stop service mysql.")
        sys.exit(-1)        
