#!/usr/bin/python
import sys

from charmhelpers.core import hookenv
from charhelplers.core import host

if __name__ == "__main__":
    if not host.service_stop("mysql"):
        hookenv.action_fail("Failed to stop service mysql.")
        sys.exit(-1)        
    try:
        override_file = open('/etc/init/mysql.override', 'w')
    except IOError, e:
        hookenv.action_fail("Error creating override file: %s\n" % e)
        sys.exit(-2)
    override_file.write("manual\n")
    override_file.close()
