#!/usr/bin/python
import os
import sys

from charmhelpers.core import hookenv
from charmhelpers.core import host

if __name__ == "__main__":
    if not host.service_resume("mysql"):
        hookenv.action_fail("Failed to start service mysql.")
        sys.exit(-1)
        

