#!/usr/bin/python
import os
import subprocess
import sys

from charmhelpers.core.hookenv import action_fail
from charmhelpers.core.host import service_start

if __name__ == "__main__":
    override_path = '/etc/init/mysql.override'
    if os.path.exists(override_path):
        try:
            os.remove(override_path)
        except OSError, e:
            action_fail("Error removing override file: %s\n" % e)
            sys.exit(-1)
    else:
        print "No override file."

    if not service_start("mysql"):
        action_fail("Failed to start service mysql.")
        sys.exit(-2)
        

